version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: coinvert-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: coinvert
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coinvert-network

  app:
    image: coinvert
    container_name: coinvert-app
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coinvert?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      JWT_SECRET: my-secret-key
    networks:
      - coinvert-network

volumes:
  mysql_data:

networks:
  coinvert-network: